services:
  web-dev:
    image: multi-env-nginx:1.0.0
    container_name: web-dev

    ports:
      - "8081:80"

    restart: unless-stopped

    networks:
      - pipeline-network

    environment:
      APP_ENV: Development
      APP_VERSION: "1.0.0"

networks:
  pipeline-network:
    external: true
