services:
  web-prod:
    image: multi-env-nginx:1.0.0
    container_name: web-prod

    ports:
      - "8083:80"

    restart: unless-stopped

    networks:
      - pipeline-network

    environment:
      APP_ENV: Production
      APP_VERSION: "1.0.0"

networks:
  pipeline-network:
    external: true
