services:
  web-staging:
    image: multi-env-nginx:1.0.0
    container_name: web-staging

    ports:
      - "8082:80"

    restart: unless-stopped

    networks:
      - pipeline-network

    environment:
      APP_ENV: Staging
      APP_VERSION: "1.0.0"

networks:
  pipeline-network:
    external: true
